### ISSUE TITLE
fetch lib signatures from Exodus Privacy, ETIP, F-Droid SUSS, etc.

### ISSUE THREAD

**Issue by eighthave** [cryptax/droidlysis#11]
There are some community maintained collections of tracker signatures that droidlysis could use as well.  For example:

* Exodus Privacy - https://github.com/Exodus-Privacy/exodus/blob/v1/doc/api.md#api-endpoints
* ETIP from Exodus Privacy - https://etip.exodus-privacy.eu.org/api/trackers/?format=json
* F-Droid SUSS - https://gitlab.com/fdroid/fdroid-suss

This is how F-Droid integrated them:
https://gitlab.com/fdroid/fdroidserver/-/merge_requests/1218/diffs

**Comment by cryptax** [comment]
You'd want this in the output to tell you: "Exodus marks this as a privacy issue" etc?

I'm not sure I want to go down the way of *detection*. DroidLysis is meant to prepare directories & help spot where to look into, not to tell you "this is malicious or not" or "this has privacy issues or not".

**Comment by eighthave** [comment]
What I mean is that it looks like that `droidlysis` is already looking for 
specific libraries, like _admob_ or other tracking libs.  Instead of maintaining 
signatures for that detection in `droidlysis`, it could fetch from from these 
other sources.

**Comment by cryptax** [comment]
Ok. Got your point. I'll work on it.

**Comment by eighthave** [comment]
Also, in ETIP and SUSS, there are expanded signature options, like `<meta-data>` identifiers.  I think that API Key IDs hold a lot of promise to be the most reliable way to detect whether a library is actually in use in an APK.  E.g. if the code signatures match, and it is configuring an API key, I can't imagine a scenario where it is not using that service.  I guess it could still be opt-in use of that service.

**Comment by cryptax** [comment]
Done. Implementation notes:

- Exodus Privacy trackers are all contained in the ETIP Exodus Privacy json link, so I am using only this link to import signatures. 
- _F-Droid SUSS_ signatures were "useless" because 1) either the `code_signature` was not provided and it wasn't certain how to create a correct signature from `gradle_signature`, or 2) already known in `kit.conf`. So, I ended up only importing a few of them by hand. Nothing is automated.

I implemented an option `--import-exodus` which will trigger:
1. **Fetch the trackers** from https://etip.exodus-privacy.eu.org/api/trackers/?format=json
2. **Compare** with current `./conf/kit.conf` and add only missing signatures. The comparison also handles less/more generic signatures.
3. **Append** the new signatures to `./conf/kit.conf` to be used for further comparison.

When `--import-exodus` is not present, the trackers from Exodus Privacy are *not* fetched nor compared.

I am not comparing with Exodus Privacy all the time because:
1. It means issuing an external HTTPS requests, which analysts might not want to do from some environments.
2. It takes a little time (not much, but a little) and seems overkill to do at each analysis.
3. In my current design, all patterns are read from `kit.conf` file. When processing Exodus trackers, I have no simple way to keep the pattern for each new tracker apart from writing it to the file.

**Comment by eighthave** [comment]
> Exodus Privacy trackers are all contained in the ETIP Exodus Privacy json link, so I am using only this link to import signatures.

I made the same decision :-) FYI, the Exodus Privacy maintainers only consider the "Exodus Privacy" data set to be officially "Exodus Privacy".  The ETIP collection is where other contributors can submit stuff for them to review.  I've been maintaining my finds in the ETIP collection.  I'm sure you could get access to edit on ETIP if you asked.

> F-Droid SUSS signatures were "useless" because 1) either the code_signature was not provided and it wasn't certain how to create a correct signature from gradle_signature, or 2) already known in kit.conf. So, I ended up only importing a few of them by hand. Nothing is automated.

SUSS has signatures for matching things in the source code, e.g. `gradle_signature` so perhaps not always relevant for _droidlysis_.  There isn't always a clean rule to map `gradle_signature` to `code_signature`, so I guess a manual import like you did makes sense for now.  We welcome merge requests to F-Droid SUS, like for adding things like `code_signatures`.

> 3. Append the new signatures to ./conf/kit.conf to be used for further comparison.

The way you implemented things seems fine, except 3 is not possible when using the Debian package since `./conf/kit.conf` from the package won't be writeable for the user.  You could either merge ETIP and `kit.conf` into  `~/.cache/droidlysis/kit.conf` or use `user_cache_dir` from the `platformdirs` lib for cross-platform support.
